### ISSUE TITLE
Floating Island coloring, PoD coloring

### ISSUE THREAD

**Issue by miketrethewey** [pickfifteen/lttp-tracker#11]
TotallyABot on Discord found some issues with coloring of Floating Island and PoD. They supplied [this picture](https://cdn.discordapp.com/attachments/369553886136107018/370364005161631751/unknown.png).

Floating Island (chest 46) is only accessible by starting in the Dark World by using any of the 3 portals available on LW Death Mountain. The current logic is met by having a glove, hammer and mirror; mirror, pearl and Titan's Mitts. This should still return "glitchavailable" since there's no Lamp in inventory.

PoD has some interesting coloring logic for chests. I was wondering if this accounted for it also being the Palace of Keys and maybe the key requirements wouldn't allow access to more chests without Lamp.

**Comment by pickfifteen** [comment]
With the last two PRs merged does this close all items raised in this issue?

**Comment by Carouelle** [comment]
I actually haven't found anything to change in PoD (so I did a commit reverting a previous one in my PR). However I think the current logic is correct, with lamp blocking 6 chests anyway.

**Comment by miketrethewey** [comment]
All I knew is that the key placement logic is complicated. If y'all determined that it's accurate to always at most six blocked without Lamp but has the potential to be less based on key placement and that's not something you could know beforehand, I think it's just a caveat that needs to be known about the Palace of Keys.
I don't know how to convey that message in a simple manner however.

**Comment by pickfifteen** [comment]
Closing all logic issues due to complete rewrite in #16. If any still exist, please open a new issue.
