### ISSUE TITLE
Corner Case Logic Issues

### ISSUE THREAD

**Issue by AllenSeitz** [pickfifteen/lttp-tracker#6]
- Ice Palace requires Firerod || (Bombos && any sword). Currently it requires Firerod || Bombos.

- Ether and Bombos tablets should be upgraded from red to yellow if the Book is found before the Master Sword.

**Comment by pickfifteen** [comment]
Should be fixed now. As always I'm not an actual runner myself so some of this logic I'm not sure about, so let me know if something's wrong.
